BlogSemanticVersion/Practice/Practice/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Entities;
using DataAccessLayer.Repository.ArticleRepository;
using DataAccessLayer.Repository.TagRepositoy;

namespace Practice.Controllers
{
    public class ArticleController : Controller
    {
        private ArticleReadRepository _articleReadRepository;

        private ArticleWriteRepository _articleWriteRepository;

        private TagReadRepository _tagReadRepository;

        public ArticleController()
        {
            _articleReadRepository = new ArticleReadRepository();
            _articleWriteRepository = new ArticleWriteRepository();
            _tagReadRepository = new TagReadRepository();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var article = _articleReadRepository.GetArticleById(id);

            var tagsExist = _tagReadRepository.GetTags();
            
            foreach (var tag in article.Tags)
            {
                if (tagsExist.Any(e => e.Content == tag.Content))
                {
                    tagsExist.Remove(tagsExist.First(e => e.Content == tag.Content));
                }
            }
            
            ViewData["tags"] = tagsExist;

            return View(article);
        }

        [HttpPost]
        public ActionResult Edit(Article article, string tags)
        {
            _articleWriteRepository.EditArticle(article, tags.Split(',').Where(e=>e.Length > 1).ToArray());
            return RedirectToAction("ShowMainForm", "Main");
        }
    }
}

BlogSemanticVersion/Practice/Practice/Views/Article/Edit.cshtml
@using System.Security.Principal
@using DataAccessLayer.Entities
@using Practice.ViewModels.Main;
@model DataAccessLayer.Entities.Article
@{
    ViewBag.Title = "Main page";
}
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script src="~/Scripts/logic/hiddenLogic.js"></script>
<script src="~/Scripts/logic/multiselectLogic.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="~/Scripts/semantic.js"></script>




<style>
    .formButton {
        width: 195px;
    }

    .img {
        position: relative;
        width: 100%;
    }

    #myCarousel {
        margin-top: 1.5%;
        border-radius: 15px;
        margin-bottom: 1.5%;
    }
</style>

<div class="row">
    <div class="ui small modal" id="modal4" style="margin-bottom:10%;margin-top:-400px;">
        <div class="col-md-12" style="margin-top:2%;">
            @using (Html.BeginForm("AddArticle", "Main", FormMethod.Post))
            {
                <h4>Add New Tag</h4>
                <div class="form-group">

                    <textarea name="TagContent" class="form-control"
                              placeholder="Enter your new tag..." pattern=".{5,}" required></textarea>
                </div>
                <button class="ui primary submit labeled icon button" type="submit" style="margin-bottom:5%;">
                    <i class="icon edit"></i> Add Tag
                </button>
            }
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-10 col-sm-offset-1">

        <div class="row">

            <div class="col-sm-8 col-sm-offset-2">

                @if (User != null && User.GetType() != typeof(WindowsPrincipal))
                {
                    <div class="column" style="margin-top: 10%;">
                        <div class="ui raised segment">
                            <div class="ui blue right ribbon label">
                                <i class="newspaper icon"></i> Add New
                            </div>

                            <h3 style="margin-top: -20px;">Write your article</h3>
                            @using (Html.BeginForm("Edit", "Article", FormMethod.Post))
                            {
                                @Html.HiddenFor(e => e.ArticleId)
                                @Html.Hidden("tags","")
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Title, new
                               {
                                   htmlAttributes = new { @class = "form-control", @placeholder = "Title for article ....", @required = "required" }
                               })
                                </div>
                                <div class="form-group">
                                    <textarea name="Content" class="form-control"
                                              placeholder="Enter your text here..." pattern=".{100,}" required>@Model.Content</textarea>
                                </div>
                                <div class="form-group included-tags">
                                    @if (Model.Tags != null)
                                    {
                                        foreach (var item in Model.Tags)
                                        {
                                            if (!String.IsNullOrEmpty(item.Content))
                                            {
                                                <a class="ui red tag label">@item.Content.Replace(" ", "_")</a>
                                            }
                                        }

                                    }
                                </div>
                                if (((IEnumerable<Tag>) ViewData["tags"]).Any())
                                 {
                                     <div class="form-group">
                                         <div style="margin-bottom: 2%;">
                                             <h4 class="excluded-container">
                                                 Select tags for your article
                                             </h4>
                                             @foreach (var tag in (IEnumerable<Tag>) ViewData["tags"])
                                             {
                                                 <span class="excluded-tag">@tag.Content</span>
                                                 <br/>
                                             }
                                         </div>
                                     </div>
                                 }
                                <div class="form-group" style="text-align: center;">

                                    <button class="ui primary submit labeled icon button formButton" type="submit" style="margin-bottom: 5%">
                                        <i class="icon edit"></i> Push article
                                    </button>
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>

        </div>
    </div>

</div>
<script>
    var template = $('<a class="ui red tag label"></a>');
    var container = $('.included-tags');

    var excludedCount = $('.excluded-tag').size();

    $(".excluded-tag").click(function (e) {
        var span = $(e.target);
        template.text(span.text()).clone().appendTo(container);

        span.remove();
        excludedCount--;

        if (excludedCount == 0) {
            $(".excluded-container").remove();
        }

        $("#tags").val($("#tags").val() + "," + span.text());
    });
</script>