BlogSemanticVersion/Practice/Practice/ViewModels/Questionary/QuestionaryFormView.cs
using System.Collections.Generic;

namespace Practice.ViewModels.Questionary
{
    public class QuestionaryFormView
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public int Age { get; set; }
        public string Mark { get; set; }
        public string Browser { get; set; }
        public string[] Preferable { get; set; }

        public string GetPreferable
        {
            get
            {
                var prefereble = "";
                foreach (var item in Preferable)
                {
                    prefereble += " " + item;
                }
                return prefereble;
            }
        }

        public List<string> ListOfCities()
        {
            var city = new List<string>();
            city.Add("Kyiv");
            city.Add("Kharkov");
            city.Add("Donetsk");
            city.Add("Lviv");
            city.Add("Dnepr");
            city.Add("Poltava");

            return city;
        }

        public List<string> ListOfBrowsers()
        {
            var browser = new List<string>();
            browser.Add("Google Chrome");
            browser.Add("Mozilla");
            browser.Add("Microsoft Edge");
            browser.Add("Opera");

            return browser;
        }
    }
}

BlogSemanticVersion/Practice/Practice/Controllers/QuestionaryController.cs
using DataAccessLayer.Entities;
using DataAccessLayer.Repository.FormRepository;
using Practice.ViewModels.Questionary;

using System.Web.Mvc;
namespace Practice.Controllers
{
    public class QuestionaryController : Controller
    {
        private readonly FormWriteRepository formWriteRepository;
        private readonly QuestionaryFormView questionaryFormView;

        public QuestionaryController()
        {
            formWriteRepository = new FormWriteRepository();
            questionaryFormView = new QuestionaryFormView();
        }

        [HttpGet]
        public ActionResult ShowQuestionaryForm()
        {
            return View(questionaryFormView);
        }

        [HttpPost]
        public ActionResult ShowQuestionaryForm(QuestionaryFormView questionary)
        {
            var newForm = new Form()
            {
                Name = questionary.Name,
                Age = questionary.Age,
                City = questionary.City,
                Email = questionary.Email,
                FavouriteBrowser = questionary.Browser,
                MarkOfForm = questionary.Mark,
                Phone = questionary.Phone,
                Preferable = questionary.GetPreferable
            };

            formWriteRepository.AddForm(newForm);
            return RedirectToAction("ShowResultForm", "Result");
        }
    }
}

BlogSemanticVersion/Practice/Practice/Views/Questionary/ShowQuestionaryForm.cshtml
@using Practice.ViewModels.Questionary;
@model QuestionaryFormView
@{ 
    ViewBag.Title = "Questionary page";
}
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script src="~/Scripts/logic/multiselectLogic.js"></script>

@helper CreateUl(string[] item)
{
    <ul>
        @foreach (var temp in item)
        {
            <li>@temp</li>
        }
    </ul>
}
<form asp-controller="Questionary" asp-action="ShowQuestionaryForm" method="post">
    <div class="container">
        <div class="ui two column grid">
            <div class="column">
                <div class="ui raised segment">
                    <a class="ui blue ribbon label">First Block</a>
                    <div class="form-group">
                        <label>1. Name </label>
                        @Html.EditorFor(model => model.Name, new
                   {
                       htmlAttributes = new { @class = "form-control", @placeholder = "Name", @required = "required" }
                   })
                    </div>

                    <div class="form-group">
                        <label>2. Phone </label>
                        @Html.EditorFor(model => model.Phone, new
                   {
                       htmlAttributes = new { @class = "form-control", @placeholder = "Phone Number", @required = "required" }
                   })
                    </div>

                    <div class="form-group">
                        <label>3. E-mail</label>
                        @Html.EditorFor(model => model.Email, new
                   {
                       htmlAttributes = new { @class = "form-control", @placeholder = "Email", @required = "required" }
                   })
                    </div>

                    <div class="form-group">
                        <label>4. City </label>
                        <select class="form-control" name="City">
                            @foreach (var item in Model.ListOfCities())
                            {
                                <option value="@item">@item</option>
                            }

                        </select>
                    </div>


                    <div class="form-group">
                        <label>5. Age</label>
                        @Html.EditorFor(model => model.Age, new
                   {
                       htmlAttributes = new { @class = "form-control", @placeholder = "Age", @required = "required" }
                   })
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="ui segment">
                    <a class="ui blue right ribbon label">Second Block</a>
                    <div class="form-group">
                        <p>
                            <b> 6. Check ur browser:</b><Br>
                            @foreach (var item in Model.ListOfBrowsers())
                            {
                                <input type="radio" name="Browser" value="@item">@item
                                <br />
                            }
                        </p>

                    </div>

                    <div class="form-group">
                        <b> 7. do u want to get info on ur email/phone ?</b><br />
                        <select id="example-selectAllName" name="Preferable" multiple="multiple">
                            @foreach (var item in Model.ListOfBrowsers())
                            {
                                <option value="@item">@item</option>
                            }
                        </select>

                    </div>

                    <div class="form-group">
                        <label> 8. was this test usefull for u?</label>
                        @CreateUl(new string[] { "0 - crap", "1-sorry for the time spent ", "2- it's ok, thank u", "3- coll stuff" })
                    </div>

                    <div class="form-group" style="margin-top:-4px;">
                        <b>Input your mark</b><br />
                        @Html.EditorFor(model => model.Mark, new
                   {
                       htmlAttributes = new { @class = "form-control", @placeholder = "Your mark is...", @required = "required" }
                   })
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-sm-4 col-sm-offset-4 form-group" style="margin-top:5%; text-align:center;">
            <button type="submit" class="ui primary submit labeled icon button" style="width:50%;">
                <i class="icon edit"></i> Finish
            </button>
        </div>
    </div>
</form>
<div>
</div>